apiVersion: v2
name: entigo-portal-agent
description: A entigo-portal-agent chart for Kubernetes
type: application
version: 0.2.21
appVersion: "0.2.21"


dependencies:
- name: developer-portal-agent
  version: 0.2.21
  repository: oci://ghcr.io/entigolabs
