apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.311

appVersion: "0.1.311"

dependencies:
  - name: platform-apis
    version: 0.1.311
    repository: oci://ghcr.io/entigolabs
