apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.251

appVersion: "0.1.251"

dependencies:
  - name: platform-apis
    version: 0.1.251
    repository: oci://ghcr.io/entigolabs

