apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.288

appVersion: "0.1.288"

dependencies:
  - name: platform-apis
    version: 0.1.288
    repository: oci://ghcr.io/entigolabs
