apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.186

appVersion: "0.1.186"

dependencies:
  - name: platform-apis
    version: 0.1.186
    repository: oci://ghcr.io/entigolabs
