apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.167

appVersion: "0.1.167"

dependencies:
  - name: platform-apis
    version: 0.1.167
    repository: oci://ghcr.io/entigolabs
