apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.188

appVersion: "0.1.188"

dependencies:
  - name: platform-apis
    version: 0.1.188
    repository: oci://ghcr.io/entigolabs
