apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.356

appVersion: "0.1.356"

dependencies:
  - name: platform-apis
    version: 0.1.6-rc.97.6.1
    repository: oci://ghcr.io/entigolabs
