apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.225

appVersion: "0.1.225"

dependencies:
  - name: platform-apis
    version: 0.1.225
    repository: oci://ghcr.io/entigolabs

