apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.233

appVersion: "0.1.233"

dependencies:
  - name: platform-apis
    version: 0.1.233
    repository: oci://ghcr.io/entigolabs

