apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.302

appVersion: "0.1.302"

dependencies:
  - name: platform-apis
    version: 0.1.302
    repository: oci://ghcr.io/entigolabs
