apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.199

appVersion: "0.1.199"

dependencies:
  - name: platform-apis
    version: 0.1.199
    repository: oci://ghcr.io/entigolabs
