apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.350

appVersion: "0.1.350"

dependencies:
  - name: platform-apis
    version: 0.1.350
    repository: oci://ghcr.io/entigolabs
