apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.252

appVersion: "0.1.252"

dependencies:
  - name: platform-apis
    version: 0.1.252
    repository: oci://ghcr.io/entigolabs

