apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.231

appVersion: "0.1.231"

dependencies:
  - name: platform-apis
    version: 0.1.231
    repository: oci://ghcr.io/entigolabs

