apiVersion: v2
name: platform-apis
description: Platform APIs
version: 0.2.11-rc.128.174.1
appVersion: "0.2.11-rc.128.174.1"
dependencies:
  - name: platform-apis
    version: 0.2.11-rc.128.174.1
    repository: oci://ghcr.io/entigolabs
