apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.295

appVersion: "0.1.295"

dependencies:
  - name: platform-apis
    version: 0.1.295
    repository: oci://ghcr.io/entigolabs
