apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.170

appVersion: "0.1.170"

dependencies:
  - name: platform-apis
    version: 0.1.170
    repository: oci://ghcr.io/entigolabs
