apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.262

appVersion: "0.1.262"

dependencies:
  - name: platform-apis
    version: 0.1.262
    repository: oci://ghcr.io/entigolabs

