apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.314

appVersion: "0.1.314"

dependencies:
  - name: platform-apis
    version: 0.1.314
    repository: oci://ghcr.io/entigolabs
