apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.198

appVersion: "0.1.198"

dependencies:
  - name: platform-apis
    version: 0.1.198
    repository: oci://ghcr.io/entigolabs
