apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.278

appVersion: "0.1.278"

dependencies:
  - name: platform-apis
    version: 0.1.278
    repository: oci://ghcr.io/entigolabs
