apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.263

appVersion: "0.1.263"

dependencies:
  - name: platform-apis
    version: 0.1.263
    repository: oci://ghcr.io/entigolabs

