apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.258

appVersion: "0.1.258"

dependencies:
  - name: platform-apis
    version: 0.1.258
    repository: oci://ghcr.io/entigolabs

