apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.303

appVersion: "0.1.303"

dependencies:
  - name: platform-apis
    version: 0.1.303
    repository: oci://ghcr.io/entigolabs
