apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.181

appVersion: "0.1.181"

dependencies:
  - name: platform-apis
    version: 0.1.181
    repository: oci://ghcr.io/entigolabs
