apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.216

appVersion: "0.1.216"

dependencies:
  - name: platform-apis
    version: 0.1.216
    repository: oci://ghcr.io/entigolabs
