apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.355

appVersion: "0.1.355"

dependencies:
  - name: platform-apis
    version: 0.1.355
    repository: oci://ghcr.io/entigolabs
