apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.229

appVersion: "0.1.229"

dependencies:
  - name: platform-apis
    version: 0.1.229
    repository: oci://ghcr.io/entigolabs
