apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.171

appVersion: "0.1.171"

dependencies:
  - name: platform-apis
    version: 0.1.171
    repository: oci://ghcr.io/entigolabs
