apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.228

appVersion: "0.1.228"

dependencies:
  - name: platform-apis
    version: 0.1.228
    repository: oci://ghcr.io/entigolabs
