apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.182

appVersion: "0.1.182"

dependencies:
  - name: platform-apis
    version: 0.1.182
    repository: oci://ghcr.io/entigolabs
