apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.305

appVersion: "0.1.305"

dependencies:
  - name: platform-apis
    version: 0.1.305
    repository: oci://ghcr.io/entigolabs
