apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.168

appVersion: "0.1.168"

dependencies:
  - name: platform-apis
    version: 0.1.168
    repository: oci://ghcr.io/entigolabs
