# .github/workflows/build-images.yaml
name: Reusable Image Builder

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
        description: "Path to image directory (e.g., images/base-tools)"
      name:
        required: true
        type: string
        description: "Image name (e.g., entigo-infralib-base-tools)"

jobs:
  build:
    name: Build image ${{ inputs.name }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Get latest release
      id: get_latest_release
      uses: actions/github-script@v6
      with:
        script: |
          const latestStableRelease = await github.rest.repos.getLatestRelease({ owner: context.repo.owner, repo: context.repo.repo });
          const versionString = '' + latestStableRelease.data.tag_name;
          const regex = /^v(\d+)\.(\d+)\.(\d+)$/;
          const match = versionString.match(regex);
          const major = parseInt(match[1], 10);
          const minor = parseInt(match[2], 10);
          const patch = parseInt(match[3], 10) + 1;
          const new_version = `v${major}.${minor}.${patch}`
          core.setOutput('new_version', new_version);

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Build and push image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_TAG: ${{ github.event_name == 'pull_request' && 'dev' || 'latest' }}
        VERSION_TAG: ${{ steps.get_latest_release.outputs.new_version }}-rc${{ github.run_number }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        aws ecr-public get-login-password --region us-east-1 | docker login -u AWS --password-stdin public.ecr.aws/entigolabs
        cd ${{ inputs.path }}
        docker buildx build --push --platform linux/arm64/v8,linux/amd64 \
          --build-arg BASE_TAG=${IMAGE_TAG} \
          -t public.ecr.aws/entigolabs/${{ inputs.name }}:${VERSION_TAG} \
          -t public.ecr.aws/entigolabs/${{ inputs.name }}:${IMAGE_TAG} \
          -t entigolabs/${{ inputs.name }}:${IMAGE_TAG} \
          -t entigolabs/${{ inputs.name }}:${VERSION_TAG} .

    - name: Create Release
      if: github.event_name == 'push'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_TAG: ${{ inputs.name }}-${{ steps.get_latest_release.outputs.new_version }}-rc${{ github.run_number }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git tag -a ${RELEASE_TAG} -m "Release ${RELEASE_TAG}"
        git push origin ${RELEASE_TAG}
        RELEASE_URL=$(gh release create ${RELEASE_TAG} \
          --title "Release ${RELEASE_TAG}" \
          --generate-notes \
          --draft=false \
          --latest=false \
          --prerelease=true)
        echo "RELEASE_URL=$RELEASE_URL" >> $GITHUB_ENV

    - name: Slack Success Release Message
      if: success() && github.event_name == 'push'
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: 'success'
        SLACK_MESSAGE: 'Released ${{ inputs.name }}-${{ steps.get_latest_release.outputs.new_version }}-rc${{ github.run_number }} ${{ env.RELEASE_URL }}'
        SLACK_USERNAME: ${{ secrets.SLACK_USERNAME }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_ICON_EMOJI: ${{ secrets.SLACK_ICON_EMOJI }}
        MSG_MINIMAL: actions url,commit
        SLACK_FOOTER: ""

    - name: Slack Failed Message
      if: failure()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: 'failure'
        SLACK_MESSAGE: 'Failed to build ${{ inputs.name }}-${{ steps.get_latest_release.outputs.new_version }}-rc${{ github.run_number }}'
        SLACK_USERNAME: ${{ secrets.SLACK_USERNAME }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_ICON_EMOJI: ${{ secrets.SLACK_ICON_EMOJI }}
        SLACK_FOOTER: ""
