name: Mirror CP AWS

on:
  push:
    branches:
      - main
    paths:
      - 'modules/k8s/crossplane-aws/pullpush.sh'
  pull_request:
    paths:
      - 'modules/k8s/crossplane-aws/pullpush.sh'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  sync-providers-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Mirror images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin && modules/k8s/crossplane-aws/pullpush.sh
      - name: Slack Success Release Message
        if: ${{ success() && github.event_name == 'push' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: 'success'
          SLACK_MESSAGE: 'Syned crossplane-aws images to Docker Hub'
          SLACK_USERNAME: ${{ secrets.SLACK_USERNAME }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_ICON_EMOJI: ${{ secrets.SLACK_ICON_EMOJI }}
          MSG_MINIMAL: actions url,commit
          SLACK_FOOTER: ""
      - name: Slack Failed Message
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: 'failure'
          SLACK_MESSAGE: 'Failed to sync crossplane-aws images to Docker Hub'
          SLACK_USERNAME: ${{ secrets.SLACK_USERNAME }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_ICON_EMOJI: ${{ secrets.SLACK_ICON_EMOJI }}
          SLACK_FOOTER: ""
