name: Build images/kubectl

on:
  push:
    branches:
      - main
    paths:
      - 'images/kubectl/**'
  pull_request:
    branches:
      - main
    paths:
      - 'images/kubectl/**'
  workflow_dispatch:
  workflow_run:
    workflows: ["Build images/tools"]
    types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build-images.yaml
    with:
      path: images/kubectl
      name: entigo-infralib-kubectl
      is_dev: ${{ github.event_name == 'pull_request' || github.event.workflow_run.event == 'pull_request' }}
    secrets: inherit
