name: Build images/kubectl

on:
  push:
    branches:
      - main
    paths:
      - 'images/kubectl/**'
  pull_request:
    branches:
      - main
    paths:
      - 'images/kubectl/**'
  workflow_dispatch:
  workflow_run:
    workflows: ["Build images/tools"]
    types: [completed]


jobs:
  build:
    uses: ./.github/workflows/build-images.yaml
    with:
      path: images/kubectl
      name: entigo-infralib-kubectl
    secrets: inherit
