name: Build images/test

on:
  push:
    branches:
      - main
    paths:
      - 'images/test/**'
  pull_request:
    branches:
      - main
    paths:
      - 'images/test/**'
  workflow_dispatch:
  workflow_run:
    workflows: ["Build images/google","Build images/aws"]
    types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build-images.yaml
    with:
      path: images/test
      name: entigo-infralib-test
    secrets: inherit
