name: Build images/base-kubectl

on:
  push:
    branches:
      - main
    paths:
      - 'images/base-kubectl/**'
  pull_request:
    branches:
      - main
    paths:
      - 'images/base-kubectl/**'
  workflow_dispatch:
  workflow_run:
    workflows: ["Build images/base-tools"]
    types: [completed]


jobs:
  build:
    uses: ./.github/workflows/build-images.yaml
    with:
      path: images/base-kubectl
      name: entigo-infralib-base-kubectl
    secrets: inherit
