name: Build images/google

on:
  push:
    branches:
      - main
    paths:
      - 'images/google/**'
  pull_request:
    branches:
      - main
    paths:
      - 'images/google/**'
  workflow_dispatch:
  workflow_run:
    workflows: ["Build images/tools"]
    types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build-images.yaml
    with:
      path: images/google
      name: entigo-infralib-google
      is_dev: ${{ github.event_name == 'pull_request' || github.event.workflow_run.event == 'pull_request' }}
    secrets: inherit
